yy4382/s3-image-port

- pages/index.vue
Add `accept="image/*"` to `UInput` so that only images are allowed to upload.
> feat: only imgs are allowed to upload

- locales/en.json
Optimize a translation on page "S3 Settings": "Test Connection" -> "Test Connectivity".
> fix(i18n): "Test Connection" -> "Test Connectivity"

- components/settings/S3.vue
Feat:
- Add an eye button to toggle the visibility of passwords.
TODO:
> feat: add eye to password input

- components/settings/S3.vue
- locales/en.json
- locales/zh.json
- pages/photos.vue
Add more toasts for `Photos` and `Settings`.
> feat: add more toasts for `Photos` and `Settings`

- components/PhotoCard.vue
- locales/en.json
- locales/zh.json
> feat: add a confirm when requesting delete

- components/settings/App.vue
- composables/useSettings.ts
- locales/en.json
- locales/zh.json
- pages/photos.vue
- types.ts
Add a switch to enable/disable the auto-update gallery feature (#29)
> feat: add switch to turn on/off auto refresh (#29)

- package.json
- pages/photos.vue
- pnpm-lock.yaml
Add a search bar.
Close #31 
TODO:
> Optimize gallery

- pages/photos.vue
Pagination issue has been solved in 7605be9.
> chore: remove finished todo comment

- components/NavMenu.vue
- locales/en.json
- locales/zh.json
- pages/photos.vue
Fixes:
- Locale on the nav menu updates correctly now
- Placeholder of the search input on the `photos` pages has its Chinese translation now
> Fix i18n issues

- components/PhotoCard.vue
> fix: prevent icons on cards from shrinking (#40)

- assets/css/global.css
- components/DropZone.vue
- components/FileBar.vue
- components/FileUploader.vue
- locales/en.json
- locales/zh.json
- nuxt.config.ts
- pages/index.vue
- types.ts
- utils/compressAndConvert.ts
- utils/genKey.ts
Feature:
- Add Drag & Drop Zone for the Upload page
- Add bars to preview or remove files to upload
Refactor:
- Move some code to the FileUploader component and refactor
> File uploader

- components/FileBar.vue
- components/FileUploader.vue
- pages/index.vue
> feat: wrapped list of upload, super long key handle and newly designed remove button

- app.vue
- components/DisplayOptions.vue
- components/NavMenu.vue
- components/ThemeSwitcher.vue
- nuxt.config.ts
- utils/getLocale.ts
- Add icons for the page switcher
- Hide text if the screen is too small
- A brand new lang switcher with a more compact and smaller appearance and simpler logic
- Global transition when switching lang and page
- A brand new light/dark switcher
@yy4382 Help! I don't know how to do these:
> Optimize the Nav Menu and i18n Experience

- components/FooterComp.vue
Features:
- Hide `Hosted on ...` and `Source at Github` on small screen
> feat: hide some elements on small screens

- utils/listObj.ts
> feat: enable get all (over 1000) objects in bucket

- components/PhotoCard.vue
- components/PhotoCard/PhotoCardModal.vue
- composables/masonry.ts
- pages/photos.vue
https://github.com/yy4382/s3-image-port/assets/55980292/4d365fcb-36ee-4c25-ab26-b5425511c96b
> Gallery layout

- components/settings/S3.vue
- locales/en.json
- locales/zh.json
Features:
- Add i18n support for the error messages on the S3 Settings page
- Add a `UAlert` containing a link to doc when the fields are not filled
> I18n Support for Error Messages on S3 Settings Page and Link to Documentation

- components/Photo/DisplayOptions.vue
Fixes:
- Bug that sort doesn't work
> Fix Bug That Sort Doesn’t Work

- app/components/ThemeSwitcher.vue
> fix: theme switcher dual icon

- app/components/settings/S3.vue
- app/locales/en.json
- app/locales/zh.json
- app/stores/settings.ts
- app/types/S3Settings.ts
- app/utils/ImageS3Client.ts
> feat: support path style s3 access

- app/components/FooterComp.vue
- app/components/NavMenu.vue
- app/components/Photo/PhotoDisplayOptions.vue
- app/components/settings/S3.vue
- app/components/settings/SettingsLayout.vue
- app/locales/en.json
- app/locales/zh.json
- app/pages/index.vue
- app/pages/upload.vue
In this PR I have tried to optimize the a11y configuration for this site. The current a11y configuration is very rudimentary (achieved by adding aria-label and role etc).
I'm having some problems implementing a11y with Nuxt UI, mainly because sometimes I can't access a specific primitive element of the wrapper component to accurately add an aria-label to that element. I don't know how to solve this problem yet.
> Optimize a11y support
